export const CONSTANTS = {
    CONTENT_TYPE_APPLICATION_JSON: "application/json",
    SIGNIN_API_URL: "/api/auth/signin",
    SIGNUP_API_URL: "/api/auth/signup",
    PROJECTS_PAGE_URL: "/projects",
    LOGIN_FAILED: "Login failed",
    SIGNUP_FAILED: "Signup failed",
    SERVER_ERROR_MESSAGE: "Something went wrong. Please try again.",
    POST_METHOD: "POST",
    SIGNUP_FORM_PAGE_URL: "/signup/form?type=",
    BACKEND_SIGNIN_URL: "http://localhost:8000/api/v1/auth/signin",
    BACKEND_SIGNUP_URL: "http://localhost:8000/api/v1/auth/signup",
    COOKIE_NAME_TOKEN: "accessToken",
    COOKIE_NAME_USERTYPE: "userType",
    PRODUCTION: "production",
    INVALID_EMAIL_OR_PASSWORD: "Invalid Email Or Password",
    SIGNOUT_FAILED: "Failed to Signout",
    SIGNOUT_SUCCESSFUL: "Signed out successfully",
    NO_TOKEN_PROVIDED: "No token provided",
    BACKEND_BUGS_URL: "http://localhost:8000/api/v1/bugs/",
    FAILED_TO_ASSIGN_BUG: "Failed to assign bug to developer",
    STATUS_REQUIRED: "Status is required",
    REQUEST_DENIED: "Request Denied",
    FAILED_TO_UPDATE_BUG_STATUS: "Failed to update bug status",
    FAILED_TO_DELETE_BUG: "Failed to delete bug",
    FAILED_TO_FETCH_BUGS: "Failed to fetch bugs",
    CONTENT_TYPE_MULTIPART_FORMDATA: "multipart/form-data",
    FAILED_TO_CREATE_BUG: "Failed to create bug",
    BACKEND_PROJECTS_URL: "http://localhost:8000/api/v1/projects/",
    FAILED_TO_FETCH_PROJECT_MEMBERS: "Failed to fetch project members",
    FAILED_TO_ASSIGN_MEMBERS_TO_PROJECT: "Failed to assign members to project",
    FAILED_TO_FETCH_PROJECT: "Failed to fetch project",
    FAILED_TO_FETCH_PROJECTS: "Failed to fetch projects",
    FAILED_TO_ADD_PROJECT: "Failed to add project",
    BACKEND_USERS_URL: "http://localhost:8000/api/v1/users",
    FAILED_TO_FETCH_USERS: "Failed to fetch users",

};